name: Test Bot

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]

# Concurrency group to prevent parallel runs
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

# This job is for testing and has no cron, so it will run only once
jobs:
  forecast_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Install dependencies
        run: poetry install --no-interaction --no-root
      
      - name: Download previous data
        uses: dawidd6/action-download-artifact@v11
        with:
          name: latest_prediction_dates_test_questions_artifact
          path: ./
          use_unzip: true
          if_no_artifact_found: warn
        continue-on-error: true
      - name: Check downloaded file
        run: |
          echo "Files in current directory:"
          ls -la
    
          if [ -f "latest_prediction_dates_test_questions.txt" ]; then
            echo "Previous data file found"
            cat latest_prediction_dates_test_questions.txt
          else
            echo "No previous data file found"
          fi
      - name: Run bot
        run: |
          poetry run python main.py --mode test_questions
        env:
          METACULUS_TOKEN: ${{ secrets.METACULUS_TOKEN }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      - name: Upload data artifact
        uses: actions/upload-artifact@v4
        with:
          name: latest_prediction_dates_test_questions_artifact
          path: latest_prediction_dates_test_questions.txt