name: Test Bot

on:
  workflow_dispatch:

# Concurrency group to prevent parallel runs
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

# This job is for testing and has no cron, so it will run only once
jobs:
  forecast_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Cache prediction log
        id: cached-prediction-log
        uses: actions/cache@v4
        with:
          path: latest_prediction_dates_test_questions.txt
          key: prediction-log-${{ github.ref }}
      - name: Install dependencies
        run: poetry install --no-interaction --no-root
      - name: Run bot
        run: |
          poetry run python main.py --mode test_questions
        env:
          METACULUS_TOKEN: ${{ secrets.METACULUS_TOKEN }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}